version: '3'

services:
  ch_server:
    image: clickhouse/clickhouse-server:22.6
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./ch_server_db:/var/lib/clickhouse
    networks:
        - ch_ntw

  nats:
    image: nats:latest
    command:
      - "--jetstream"
      - "--http_port"
      - "8222"
    environment:
      NATS_HTTP_PORT_NUMBER: 8222
    expose:
      - "4222"
    ports:
      - "8222:8222"
      - "4222:4222"
    networks:
        - ch_ntw

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    networks:
        - ch_ntw

networks:
  ch_ntw:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 10.222.1.0/24
